### ISSUE TITLE
How can I use mask with infinite characters?

### ISSUE THREAD

**Issue by AshileySabah** [GoncharukBro/react-mask-field#3]
I want to implement a mask that accepts only numbers and my input doesn't have a specific length, you can type as many characters as you want so it wouldn't make sense to use mask="_" and a replacement={{ _: /\d/ }}, because it would only allow me 1 character. What can I do?

**Comment by GoncharukBro** [comment]
This component only responds to the mask pattern you specified, you can modify the component's properties at the time of input, but this will not give a good result. Now work is underway to update the library where there will be a component that will meet your desires.
